name: Go CI

on:
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ 1.21.x ]

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Get dependencies
        run: |
          go mod download
          go mod verify

      - name: Build
        if: ${{ success() }}
        run: go build -v -p 4 ./cmd/main.go